"use client";

import { useState, useMemo, useCallback } from "react";
import type { Article } from "@/types";

interface WeeklyReportProps {
  open: boolean;
  onClose: () => void;
  articles: Article[];
  portfolioPrices?: Array<{ symbol: string; label: string; price: number; change: number; changePct: number }>;
}

// Korean particles to exclude from keyword analysis
const KOREAN_PARTICLES = new Set([
  "은", "는", "이", "가", "을", "를", "에", "의", "와", "과", "도", "로",
  "에서", "으로", "에게", "한", "된", "하는", "있는", "대한", "위한", "등",
  "및", "또는", "그", "이번", "지난", "올해", "내년", "수", "것", "중",
]);

function getWeekRange(): { start: Date; end: Date; label: string } {
  const now = new Date();
  const end = new Date(now);
  const start = new Date(now);
  start.setDate(start.getDate() - 6);
  const fmt = (d: Date) =>
    `${d.getFullYear()}.${String(d.getMonth() + 1).padStart(2, "0")}.${String(d.getDate()).padStart(2, "0")}`;
  return { start, end, label: `${fmt(start)} — ${fmt(end)}` };
}

function extractKeywords(titles: string[], topN = 12): { word: string; count: number }[] {
  const freq = new Map<string, number>();
  for (const title of titles) {
    // Split on whitespace, punctuation, quotes, brackets
    const words = title
      .replace(/["""'''\[\](){}「」『』〈〉《》·…—–\-,.:;!?%\d]/g, " ")
      .split(/\s+/)
      .filter((w) => w.length >= 2 && !KOREAN_PARTICLES.has(w));
    for (const w of words) {
      freq.set(w, (freq.get(w) || 0) + 1);
    }
  }
  return Array.from(freq.entries())
    .filter(([, c]) => c >= 2)
    .sort((a, b) => b[1] - a[1])
    .slice(0, topN)
    .map(([word, count]) => ({ word, count }));
}

function generateMarkdown(
  weekLabel: string,
  totalArticles: number,
  sourceCounts: { name: string; count: number }[],
  mostActiveDay: string,
  readRate: number,
  savedRate: number,
  topStories: Article[],
  tagBreakdown: { tag: string; count: number }[],
  keywords: { word: string; count: number }[],
  prices?: Array<{ symbol: string; label: string; price: number; change: number; changePct: number }>
): string {
  let md = `# MacroWire WEEKLY REPORT\n\n> ${weekLabel}\n\n---\n\n`;

  md += `## OVERVIEW\n\n`;
  md += `- 총 기사: **${totalArticles}건**\n`;
  md += `- 가장 활발한 날: **${mostActiveDay}**\n`;
  md += `- 읽음률: **${readRate.toFixed(1)}%** · 저장률: **${savedRate.toFixed(1)}%**\n\n`;

  if (sourceCounts.length > 0) {
    md += `### 소스별 기사 수\n\n`;
    sourceCounts.forEach((s) => {
      md += `- ${s.name}: ${s.count}건\n`;
    });
    md += `\n`;
  }

  if (topStories.length > 0) {
    md += `## TOP STORIES\n\n`;
    topStories.forEach((a, i) => {
      md += `${i + 1}. **${a.title}**\n   ${a.sourceName} · ${new Date(a.publishedAt).toLocaleDateString("ko-KR")}\n\n`;
    });
  }

  if (tagBreakdown.length > 0) {
    md += `## TAG BREAKDOWN\n\n`;
    tagBreakdown.forEach((t) => {
      md += `- ${t.tag}: ${t.count}건\n`;
    });
    md += `\n`;
  }

  if (prices && prices.length > 0) {
    md += `## MARKET SUMMARY\n\n`;
    prices.forEach((p) => {
      const sign = p.change >= 0 ? "+" : "";
      md += `- ${p.symbol}: ${p.price.toLocaleString()} (${sign}${p.changePct.toFixed(2)}%)\n`;
    });
    md += `\n`;
  }

  if (keywords.length > 0) {
    md += `## TRENDING KEYWORDS\n\n`;
    keywords.forEach((k) => {
      md += `- ${k.word} (${k.count})\n`;
    });
    md += `\n`;
  }

  md += `---\n\nGenerated by MacroWire\n`;
  return md;
}

function generateHTML(
  weekLabel: string,
  totalArticles: number,
  sourceCounts: { name: string; count: number }[],
  mostActiveDay: string,
  readRate: number,
  savedRate: number,
  topStories: Article[],
  tagBreakdown: { tag: string; count: number }[],
  keywords: { word: string; count: number }[],
  prices?: Array<{ symbol: string; label: string; price: number; change: number; changePct: number }>
): string {
  const tagMax = tagBreakdown.length > 0 ? tagBreakdown[0].count : 1;
  return `<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>MacroWire WEEKLY REPORT</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;600;700&family=Space+Mono:wght@400;700&display=swap');
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { background: var(--background); color: var(--foreground); font-family: 'Pretendard Variable', Pretendard, -apple-system, BlinkMacSystemFont, system-ui, sans-serif; padding: 40px 20px; }
  .container { max-width: 800px; margin: 0 auto; }
  h1 { color: var(--accent); font-size: 24px; letter-spacing: 0.08em; font-weight: 700; margin-bottom: 4px; }
  .date-range { color: var(--muted); font-family: var(--font-mono), ui-monospace, monospace; font-size: 13px; margin-bottom: 32px; }
  .section { margin-bottom: 32px; }
  .section-label { font-size: 11px; font-weight: 700; color: var(--muted); letter-spacing: 0.1em; text-transform: uppercase; margin-bottom: 12px; border-bottom: 1px solid var(--border); padding-bottom: 8px; }
  .stat-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; }
  .stat-card { background: var(--surface-raised); border: 1px solid var(--border); padding: 16px; }
  .stat-value { font-family: var(--font-mono), ui-monospace, monospace; font-size: 22px; font-weight: 700; color: var(--accent); }
  .stat-label { font-size: 11px; color: var(--muted); margin-top: 4px; }
  .story-item { padding: 12px 0; border-bottom: 1px solid var(--border); }
  .story-num { font-family: var(--font-mono), ui-monospace, monospace; color: var(--accent); font-size: 13px; font-weight: 700; }
  .story-title { font-size: 14px; font-weight: 600; margin-left: 8px; }
  .story-meta { font-size: 11px; color: var(--muted); margin-top: 4px; margin-left: 24px; }
  .tag-row { display: flex; align-items: center; gap: 8px; margin-bottom: 6px; }
  .tag-name { font-size: 12px; width: 80px; text-align: right; color: var(--muted); }
  .tag-bar { height: 16px; background: color-mix(in srgb, var(--accent) 30%, transparent); border-right: 2px solid var(--accent); }
  .tag-count { font-family: var(--font-mono), ui-monospace, monospace; font-size: 11px; color: var(--muted); margin-left: 4px; }
  .keyword-list { display: flex; flex-wrap: wrap; gap: 8px; }
  .keyword { background: var(--surface-raised); border: 1px solid var(--border); padding: 4px 10px; font-size: 12px; }
  .keyword-count { font-family: var(--font-mono), ui-monospace, monospace; color: var(--accent); font-size: 10px; margin-left: 4px; }
  .market-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid var(--border); font-size: 13px; }
  .market-symbol { color: var(--foreground); font-weight: 600; }
  .market-price { font-family: var(--font-mono), ui-monospace, monospace; }
  .market-change-up { color: var(--success); }
  .market-change-down { color: var(--danger); }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid var(--border); font-size: 11px; color: var(--muted); text-align: center; }
  @media print { body { background: #fff; color: #1a1a1a; } .stat-card { border-color: #ddd; background: var(--foreground-bright); } .stat-value { color: var(--accent-dim); } h1 { color: var(--accent-dim); } .section-label { color: #666; border-color: #ddd; } .story-num { color: var(--accent-dim); } .tag-bar { background: rgba(139,105,20,0.2); border-color: var(--accent-dim); } .keyword { border-color: #ddd; background: var(--foreground-bright); } .keyword-count { color: var(--accent-dim); } .market-row { border-color: #ddd; } .footer { border-color: #ddd; } }
</style>
</head>
<body>
<div class="container">
  <h1>MacroWire WEEKLY REPORT</h1>
  <div class="date-range">${weekLabel}</div>

  <div class="section">
    <div class="section-label">요약</div>
    <div class="stat-grid">
      <div class="stat-card"><div class="stat-value">${totalArticles}</div><div class="stat-label">총 기사</div></div>
      <div class="stat-card"><div class="stat-value">${sourceCounts.length}</div><div class="stat-label">활성 소스</div></div>
      <div class="stat-card"><div class="stat-value">${readRate.toFixed(0)}%</div><div class="stat-label">읽음률</div></div>
      <div class="stat-card"><div class="stat-value">${savedRate.toFixed(0)}%</div><div class="stat-label">저장률</div></div>
    </div>
    <div style="margin-top:12px;font-size:12px;color:var(--muted)">가장 활발한 날: <span style="color:var(--foreground);font-weight:600">${mostActiveDay}</span></div>
  </div>

  ${topStories.length > 0 ? `
  <div class="section">
    <div class="section-label">주요 기사</div>
    ${topStories.map((a, i) => `
    <div class="story-item">
      <span class="story-num">${String(i + 1).padStart(2, "0")}</span>
      <span class="story-title">${a.title}</span>
      <div class="story-meta">${a.sourceName} · ${new Date(a.publishedAt).toLocaleDateString("ko-KR")}</div>
    </div>`).join("")}
  </div>` : ""}

  ${tagBreakdown.length > 0 ? `
  <div class="section">
    <div class="section-label">태그 분포</div>
    ${tagBreakdown.map((t) => `
    <div class="tag-row">
      <span class="tag-name">${t.tag}</span>
      <div class="tag-bar" style="width:${Math.max(4, (t.count / tagMax) * 300)}px"></div>
      <span class="tag-count">${t.count}</span>
    </div>`).join("")}
  </div>` : ""}

  ${sourceCounts.length > 0 ? `
  <div class="section">
    <div class="section-label">소스 활동</div>
    ${sourceCounts.map((s) => `
    <div class="tag-row">
      <span class="tag-name">${s.name}</span>
      <div class="tag-bar" style="width:${Math.max(4, (s.count / (sourceCounts[0]?.count || 1)) * 300)}px"></div>
      <span class="tag-count">${s.count}</span>
    </div>`).join("")}
  </div>` : ""}

  ${prices && prices.length > 0 ? `
  <div class="section">
    <div class="section-label">시장 요약</div>
    ${prices.map((p) => {
      const sign = p.change >= 0 ? "+" : "";
      const cls = p.change >= 0 ? "market-change-up" : "market-change-down";
      return `
    <div class="market-row">
      <span class="market-symbol">${p.symbol}</span>
      <span class="market-price">${p.price.toLocaleString()} <span class="${cls}">${sign}${p.changePct.toFixed(2)}%</span></span>
    </div>`;
    }).join("")}
  </div>` : ""}

  ${keywords.length > 0 ? `
  <div class="section">
    <div class="section-label">많이 다뤄진 키워드</div>
    <div class="keyword-list">
      ${keywords.map((k) => `<span class="keyword">${k.word}<span class="keyword-count">${k.count}</span></span>`).join("")}
    </div>
  </div>` : ""}

  <div class="footer">Powered by MacroWire</div>
</div>
</body>
</html>`;
}

export function WeeklyReport({ open, onClose, articles, portfolioPrices }: WeeklyReportProps) {
  const [copied, setCopied] = useState(false);

  const week = useMemo(() => getWeekRange(), []);

  // Filter articles to this week
  const weekArticles = useMemo(() => {
    const start = week.start.getTime();
    const end = week.end.getTime() + 86400000; // include end day
    return articles.filter((a) => {
      const t = new Date(a.publishedAt).getTime();
      return t >= start && t <= end;
    });
  }, [articles, week]);

  const totalArticles = weekArticles.length;

  const sourceCounts = useMemo(() => {
    const map = new Map<string, number>();
    weekArticles.forEach((a) => map.set(a.sourceName, (map.get(a.sourceName) || 0) + 1));
    return Array.from(map.entries())
      .map(([name, count]) => ({ name, count }))
      .sort((a, b) => b.count - a.count);
  }, [weekArticles]);

  const mostActiveDay = useMemo(() => {
    const dayMap = new Map<string, number>();
    weekArticles.forEach((a) => {
      const d = new Date(a.publishedAt).toLocaleDateString("ko-KR", { weekday: "long", month: "numeric", day: "numeric" });
      dayMap.set(d, (dayMap.get(d) || 0) + 1);
    });
    let max = 0;
    let maxDay = "-";
    dayMap.forEach((count, day) => {
      if (count > max) { max = count; maxDay = day; }
    });
    return maxDay;
  }, [weekArticles]);

  const readRate = totalArticles > 0 ? (weekArticles.filter((a) => a.isRead).length / totalArticles) * 100 : 0;
  const savedRate = totalArticles > 0 ? (weekArticles.filter((a) => a.isSaved).length / totalArticles) * 100 : 0;

  const topStories = useMemo(() => {
    return [...weekArticles]
      .filter((a) => a.isSaved)
      .sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime())
      .slice(0, 5);
  }, [weekArticles]);

  const tagBreakdown = useMemo(() => {
    const map = new Map<string, number>();
    weekArticles.forEach((a) => a.tags.forEach((t) => map.set(t, (map.get(t) || 0) + 1)));
    return Array.from(map.entries())
      .map(([tag, count]) => ({ tag, count }))
      .sort((a, b) => b.count - a.count);
  }, [weekArticles]);

  const keywords = useMemo(() => {
    return extractKeywords(weekArticles.map((a) => a.title));
  }, [weekArticles]);

  const tagMax = tagBreakdown.length > 0 ? tagBreakdown[0].count : 1;

  const handleCopyMarkdown = useCallback(() => {
    const md = generateMarkdown(
      week.label, totalArticles, sourceCounts, mostActiveDay,
      readRate, savedRate, topStories, tagBreakdown, keywords, portfolioPrices
    );
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [week, totalArticles, sourceCounts, mostActiveDay, readRate, savedRate, topStories, tagBreakdown, keywords, portfolioPrices]);

  const handleExportHTML = useCallback(() => {
    const html = generateHTML(
      week.label, totalArticles, sourceCounts, mostActiveDay,
      readRate, savedRate, topStories, tagBreakdown, keywords, portfolioPrices
    );
    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `macro-wire-weekly-report-${new Date().toISOString().slice(0, 10)}.html`;
    link.click();
    URL.revokeObjectURL(url);
  }, [week, totalArticles, sourceCounts, mostActiveDay, readRate, savedRate, topStories, tagBreakdown, keywords, portfolioPrices]);

  const handlePrint = useCallback(() => {
    window.print();
  }, []);

  if (!open) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-start justify-center pt-[4vh] overflow-y-auto"
      style={{ background: "rgba(0,0,0,0.5)", backdropFilter: "blur(4px)" }}
      onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div
        className="w-full mb-8"
        style={{
          maxWidth: 800,
          background: "var(--background)",
          border: "1px solid var(--border)",
          minHeight: 400,
        }}
      >
        {/* Header */}
        <div
          className="flex items-center justify-between px-6 py-4"
          style={{ borderBottom: "1px solid var(--border)" }}
        >
          <div>
            <h1
              className="font-heading"
              style={{ color: "var(--accent)", fontSize: 20, letterSpacing: "0.08em", fontWeight: 700 }}
            >
              MacroWire WEEKLY REPORT
            </h1>
            <p style={{ fontFamily: "var(--font-mono), ui-monospace, monospace", fontSize: 12, color: "var(--muted)", marginTop: 2 }}>
              {week.label}
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyMarkdown}
              className="flex items-center gap-1.5 px-3 py-1.5 text-[11px] font-medium transition-colors"
              style={{
                border: "1px solid var(--border)",
                background: copied ? "color-mix(in srgb, var(--accent) 15%, transparent)" : "transparent",
                color: copied ? "var(--accent)" : "var(--muted)",
              }}
            >
              {copied ? "복사됨" : "Markdown로 복사"}
            </button>
            <button
              onClick={handleExportHTML}
              className="flex items-center gap-1.5 px-3 py-1.5 text-[11px] font-medium transition-colors"
              style={{ border: "1px solid var(--border)", background: "transparent", color: "var(--muted)" }}
            >
              HTML로 내보내기
            </button>
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 text-[11px] font-medium transition-colors"
              style={{ border: "1px solid var(--border)", background: "transparent", color: "var(--muted)" }}
            >
              인쇄
            </button>
            <button
              onClick={onClose}
              className="flex items-center justify-center w-7 h-7 text-[var(--muted)] hover:text-[var(--foreground)] transition-colors"
            >
              <svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.5">
                <path d="M1 1l12 12M13 1L1 13" />
              </svg>
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="px-6 py-5 space-y-6">
          {/* Overview Stats */}
          <div>
            <div
              className="font-heading"
              style={{
                fontSize: 10,
                fontWeight: 700,
                color: "var(--muted)",
                letterSpacing: "0.1em",
                textTransform: "uppercase" as const,
                marginBottom: 10,
                paddingBottom: 6,
                borderBottom: "1px solid var(--border)",
              }}
            >요약</div>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 10 }}>
              {[
                { value: totalArticles, label: "총 기사" },
                { value: sourceCounts.length, label: "활성 소스" },
                { value: `${readRate.toFixed(0)}%`, label: "읽음률" },
                { value: `${savedRate.toFixed(0)}%`, label: "저장률" },
              ].map((s) => (
                <div
                  key={s.label}
                  style={{ background: "var(--surface-raised)", border: "1px solid var(--border)", padding: "14px 16px" }}
                >
                  <div style={{ fontFamily: "var(--font-mono), ui-monospace, monospace", fontSize: 22, fontWeight: 700, color: "var(--accent)" }}>
                    {s.value}
                  </div>
                  <div style={{ fontSize: 11, color: "var(--muted)", marginTop: 2 }}>{s.label}</div>
                </div>
              ))}
            </div>
            <div style={{ marginTop: 8, fontSize: 11, color: "var(--muted)" }}>
              가장 활발한 날: <span style={{ color: "var(--foreground)", fontWeight: 600 }}>{mostActiveDay}</span>
            </div>
          </div>

          {/* Top Stories */}
          {topStories.length > 0 && (
            <div>
              <div
                className="font-heading"
                style={{
                  fontSize: 10,
                  fontWeight: 700,
                  color: "var(--muted)",
                  letterSpacing: "0.1em",
                  textTransform: "uppercase" as const,
                  marginBottom: 10,
                  paddingBottom: 6,
                  borderBottom: "1px solid var(--border)",
                }}
              >주요 기사</div>
              {topStories.map((a, i) => (
                <div key={a.id} style={{ padding: "10px 0", borderBottom: "1px solid var(--border)" }}>
                  <span style={{ fontFamily: "var(--font-mono), ui-monospace, monospace", color: "var(--accent)", fontSize: 12, fontWeight: 700 }}>
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <span style={{ fontSize: 13, fontWeight: 600, marginLeft: 8, color: "var(--foreground)" }}>{a.title}</span>
                  <div style={{ fontSize: 11, color: "var(--muted)", marginTop: 3, marginLeft: 24 }}>
                    {a.sourceName} · {new Date(a.publishedAt).toLocaleDateString("ko-KR")}
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Tag Breakdown */}
          {tagBreakdown.length > 0 && (
            <div>
              <div
                className="font-heading"
                style={{
                  fontSize: 10,
                  fontWeight: 700,
                  color: "var(--muted)",
                  letterSpacing: "0.1em",
                  textTransform: "uppercase" as const,
                  marginBottom: 10,
                  paddingBottom: 6,
                  borderBottom: "1px solid var(--border)",
                }}
              >태그 분포</div>
              {tagBreakdown.map((t) => (
                <div key={t.tag} style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 5 }}>
                  <span style={{ fontSize: 11, width: 80, textAlign: "right", color: "var(--muted)" }}>{t.tag}</span>
                  <div
                    style={{
                      height: 14,
                      background: "color-mix(in srgb, var(--accent) 25%, transparent)",
                      borderRight: "2px solid var(--accent)",
                      width: Math.max(4, (t.count / tagMax) * 300),
                      transition: "width 0.3s",
                    }}
                  />
                  <span style={{ fontFamily: "var(--font-mono), ui-monospace, monospace", fontSize: 10, color: "var(--muted)" }}>{t.count}</span>
                </div>
              ))}
            </div>
          )}

          {/* Source Activity */}
          {sourceCounts.length > 0 && (
            <div>
              <div
                className="font-heading"
                style={{
                  fontSize: 10,
                  fontWeight: 700,
                  color: "var(--muted)",
                  letterSpacing: "0.1em",
                  textTransform: "uppercase" as const,
                  marginBottom: 10,
                  paddingBottom: 6,
                  borderBottom: "1px solid var(--border)",
                }}
              >소스 활동</div>
              {sourceCounts.map((s) => (
                <div key={s.name} style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 5 }}>
                  <span style={{ fontSize: 11, width: 120, textAlign: "right", color: "var(--muted)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                    {s.name}
                  </span>
                  <div
                    style={{
                      height: 14,
                      background: "color-mix(in srgb, var(--accent) 25%, transparent)",
                      borderRight: "2px solid var(--accent)",
                      width: Math.max(4, (s.count / (sourceCounts[0]?.count || 1)) * 250),
                      transition: "width 0.3s",
                    }}
                  />
                  <span style={{ fontFamily: "var(--font-mono), ui-monospace, monospace", fontSize: 10, color: "var(--muted)" }}>{s.count}</span>
                </div>
              ))}
            </div>
          )}

          {/* Market Summary */}
          {portfolioPrices && portfolioPrices.length > 0 && (
            <div>
              <div
                className="font-heading"
                style={{
                  fontSize: 10,
                  fontWeight: 700,
                  color: "var(--muted)",
                  letterSpacing: "0.1em",
                  textTransform: "uppercase" as const,
                  marginBottom: 10,
                  paddingBottom: 6,
                  borderBottom: "1px solid var(--border)",
                }}
              >시장 요약</div>
              {portfolioPrices.map((p) => {
                const sign = p.change >= 0 ? "+" : "";
                const color = p.change >= 0 ? "var(--success)" : "var(--danger)";
                return (
                  <div
                    key={p.symbol}
                    style={{ display: "flex", justifyContent: "space-between", padding: "7px 0", borderBottom: "1px solid var(--border)", fontSize: 12 }}
                  >
                    <span style={{ fontWeight: 600 }}>{p.symbol}</span>
                    <span style={{ fontFamily: "var(--font-mono), ui-monospace, monospace" }}>
                      {p.price.toLocaleString()}{" "}
                      <span style={{ color }}>{sign}{p.changePct.toFixed(2)}%</span>
                    </span>
                  </div>
                );
              })}
            </div>
          )}

          {/* Trending Keywords */}
          {keywords.length > 0 && (
            <div>
              <div
                className="font-heading"
                style={{
                  fontSize: 10,
                  fontWeight: 700,
                  color: "var(--muted)",
                  letterSpacing: "0.1em",
                  textTransform: "uppercase" as const,
                  marginBottom: 10,
                  paddingBottom: 6,
                  borderBottom: "1px solid var(--border)",
                }}
              >많이 다뤄진 키워드</div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
                {keywords.map((k) => (
                  <span
                    key={k.word}
                    style={{
                      background: "var(--surface-raised)",
                      border: "1px solid var(--border)",
                      padding: "4px 10px",
                      fontSize: 11,
                      color: "var(--foreground)",
                    }}
                  >
                    {k.word}
                    <span style={{ fontFamily: "var(--font-mono), ui-monospace, monospace", color: "var(--accent)", fontSize: 10, marginLeft: 4 }}>
                      {k.count}
                    </span>
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Empty state */}
          {totalArticles === 0 && (
            <div style={{ textAlign: "center", padding: "40px 0", color: "var(--muted)", fontSize: 13 }}>
              이번 주 수집된 기사가 없습니다.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
